---
- name: "create config directories"
  file:
    path: "{{ openvpn_conf_path }}/server"
    state: directory
    mode: '0755'

- name: "copy config files"
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_conf_path }}/server/"
    force: true
    mode: 0644
  with_fileglob: "{{ openvpn_config_files }}"

- name: "copy easy-rsa vars file"
  copy:
    src: "{{ openvpn_easyrsa_vars_file }}"
    dest: "{{ openvpn_conf_path }}/easy-rsa/easyrsa3/vars"
    force: true
    mode: 0644
  when: openvpn_easyrsa_vars_file | length > 0
